### ISSUE TITLE
docker-compose up   

### ISSUE THREAD

**Issue by chenyongze** [easy-swoole/kafka#14]
kafka1_1         | [2020-02-11 07:51:33,189] WARN [Controller id=1002, targetBrokerId=1001] Connection to node 1001 (/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

**Comment by Manlinup** [comment]
I haven't met the situation you said. It is suggested that you search relevant materials for solutions.
Such as https://blog.csdn.net/matrix_google/article/details/86684832
